"""Add vote to Subjiect

Revision ID: abf7a38cf01a
Revises: 
Create Date: 2024-12-11 18:58:01.245373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf7a38cf01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjiect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjiect', schema=None) as batch_op:
        batch_op.drop_column('vote')

    # ### end Alembic commands ###
